First draft for preproccessing Morocco legislation
danpdraper/eia pull request #44
Opened 2021-09-19 02:09 UTC by Skyrolon

Issues I was not able to resolve:

1. Article 1: I'm not sure how to turn all the '-' into bullet points in an efficient one. I can do them one by one, but I can't figure out how to do replace all in one paragraph.
2. Article 3: I'm not sure how you want me to handle that or if the formatting is fine as it is.
3. Article 3: There is a footnote ("* - Dahir N° 1.03.59 du 10 Rabiï I 1424 (12 mai [2003], BO N° 5118 du Juin 2003 2") that I'm not sure how to remove. I think some of the symbols might be messing it up.\
4. I ran a spellcheck in word and it only detected one missed accent. My french is basically non-existent at this level so I'm not sure if there are more errors or a better spellchecker I should use.

Closes Issue #35

2021-09-19 21:44 UTC, danpdraper commented on raw_data/preprocessed/africa/morocco_french.txt
> +(1) La présente loi a pour objet d'édicter les règles de base et les principes généraux de la politique nationale dans le domaine de la protection et de la mise en valeur de l'environnement. Ces règl
You can replace all of the dashes with bullet points with the following command:

```
sed -E ':start s/^(\(1\).*)- /\1• /;t start'
```

2021-09-19 21:47 UTC, danpdraper commented on raw_data/preprocessed/africa/morocco_french.txt
> +(2) L'application des dispositions de la présente loi se base sur les principes généraux suivants: [•] La protection, la mise en valeur et la bonne gestion de l'environnement font partie de la politi
Please remove the unnecessary spacing around the double quotation marks in `" l'usager payeur "` and `" du pollueur payeur "`.

2021-09-19 22:05 UTC, danpdraper requested changes

2021-09-19 22:05 UTC, danpdraper commented on raw_data/preprocessed/africa/morocco_french.txt
> +(3) Au sens de la présente loi on entend par: 1 - Environnement: l'ensemble des éléments naturels et des établissements humains ainsi que les facteurs économiques, sociaux et culturels favorisant l'e
Please remove all of the numbers and hyphens that precede each defined phrase.

You can remove `* - Dahir N° 1.03.59 du 10 Rabiï I 1424 (12 mai [2003], BO N° 5118 du Juin 2003 2` with the following command:

```
amend_error_in_article '\* - Dahir.*Etablissements humains' 'Établissements humains'
```

2021-09-19 22:05 UTC, danpdraper commented on raw_data/preprocessed/africa/morocco_french.txt
> +(2) L'application des dispositions de la présente loi se base sur les principes généraux suivants: [•] La protection, la mise en valeur et la bonne gestion de l'environnement font partie de la politi
Please remove the unnecessary spacing around the double quotation marks in `" l'usager payeur "` and `" du pollueur payeur "`.

2021-09-19 22:05 UTC, danpdraper commented on raw_data/preprocessed/africa/morocco_french.txt
> +(1) La présente loi a pour objet d'édicter les règles de base et les principes généraux de la politique nationale dans le domaine de la protection et de la mise en valeur de l'environnement. Ces règl
You can replace all of the dashes with bullet points with the following command:

```
sed -E ':start;s/^(\(1\).*)- /\1• /;t start'
```

2021-09-19 22:05 UTC, danpdraper commented on raw_data/preprocessed/africa/morocco_french.txt
> +(34) Les dispositions législatives et réglementaires fixent: [•] les conditions d'exploration, d'exploitation et de mise en valeur des ressources marines; [•] les mesures nécessaires pour la préventi
Is there a bullet point missing before `les critères nécessaires`?

2021-09-19 22:05 UTC, danpdraper commented on raw_data/preprocessed/africa/morocco_french.txt
> +(36) Les dispositions législatives et réglementaires fixent les mécanismes et les moyens de protection des espaces et ressources marins, notamment:- les modalités d'élaboration des schémas et des pla
Two hyphens need to be replaced with bullet points in this article.

2021-09-19 22:05 UTC, danpdraper commented on raw_data/preprocessed/africa/morocco_french.txt
> +(37) En vue de la protection du monde rural, la conservation et la mise en valeur des écosystèmes dans les campagnes et les zones montagneuses, des dispositions législatives et réglementaires sont pr
The hyphens need to be replaced with bullet points in this article.

2021-09-19 22:05 UTC, danpdraper commented on scripts/legislation/africa/morocco_french.sh
> +#!/bin/bash
I'll review this file after you have addressed the comments above.

2021-09-19 23:56 UTC, merged

2021-09-20 18:45 UTC, Skyrolon commented on raw_data/preprocessed/africa/morocco_french.txt
> +(34) Les dispositions législatives et réglementaires fixent: [•] les conditions d'exploration, d'exploitation et de mise en valeur des ressources marines; [•] les mesures nécessaires pour la préventi
The [legislation](http://extwprlegs1.fao.org/docs/pdf/mor42766.pdf) does not contain a bullet point, but I am inclined to believe this is an oversight on their part. Do you want me to add one in?

2021-09-20 18:49 UTC, Skyrolon commented on raw_data/preprocessed/africa/morocco_french.txt
> +(1) La présente loi a pour objet d'édicter les règles de base et les principes généraux de la politique nationale dans le domaine de la protection et de la mise en valeur de l'environnement. Ces règl
There seems to be some inconsistency between the bullet point formats used in the scripts. I see that [•] is normally used, but here you use • (there are no brackets). Is there a format we should use consistently?

2021-09-20 19:05 UTC, danpdraper commented on raw_data/preprocessed/africa/morocco_french.txt
> +(1) La présente loi a pour objet d'édicter les règles de base et les principes généraux de la politique nationale dans le domaine de la protection et de la mise en valeur de l'environnement. Ces règl
Sorry, there should be square brackets around the bullet point. Please use the following command:

```
sed -E ':start;s/^(\(1\).*)- /\1[•] /;t start'
```

2021-09-20 19:06 UTC, danpdraper commented on raw_data/preprocessed/africa/morocco_french.txt
> +(34) Les dispositions législatives et réglementaires fixent: [•] les conditions d'exploration, d'exploitation et de mise en valeur des ressources marines; [•] les mesures nécessaires pour la préventi
Yes, please.

2021-09-24 18:13 UTC, danpdraper commented on raw_data/preprocessed/africa/morocco_french.txt
> +(1) La présente loi a pour objet d'édicter les règles de base et les principes généraux de la politique nationale dans le domaine de la protection et de la mise en valeur de l'environnement. Ces règl
This doesn't appear to have been fixed in the new pull request.

2021-09-24 18:13 UTC, danpdraper commented on raw_data/preprocessed/africa/morocco_french.txt
> +(2) L'application des dispositions de la présente loi se base sur les principes généraux suivants: [•] La protection, la mise en valeur et la bonne gestion de l'environnement font partie de la politi
This doesn't appear to have been fixed in the new pull request.

2021-09-24 18:14 UTC, danpdraper commented on raw_data/preprocessed/africa/morocco_french.txt
> +(3) Au sens de la présente loi on entend par: 1 - Environnement: l'ensemble des éléments naturels et des établissements humains ainsi que les facteurs économiques, sociaux et culturels favorisant l'e
This provision still contains all of the numbers and hyphens in the new pull request.

2021-09-24 18:15 UTC, danpdraper commented on raw_data/preprocessed/africa/morocco_french.txt
> +(36) Les dispositions législatives et réglementaires fixent les mécanismes et les moyens de protection des espaces et ressources marins, notamment:- les modalités d'élaboration des schémas et des pla
This doesn't appear to have been fixed in the new pull request.

2021-09-24 18:15 UTC, danpdraper commented on raw_data/preprocessed/africa/morocco_french.txt
> +(37) En vue de la protection du monde rural, la conservation et la mise en valeur des écosystèmes dans les campagnes et les zones montagneuses, des dispositions législatives et réglementaires sont pr
This doesn't appear to have been fixed in the new pull request.